name: run unit tests of feature branch

on:
  push:
    branches:
      'feature/*'

jobs:
  runUnitTests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: runUnitTest
        run: mvn test
      
      
      
